Low: aws-vpc-route53: Fix missing ocf_log in log message

diff --git a/heartbeat/aws-vpc-route53 b/heartbeat/aws-vpc-route53
--- a/heartbeat/aws-vpc-route53
+++ b/heartbeat/aws-vpc-route53
@@ -174,7 +174,7 @@ ec2ip_validate() {
 	debugger "Testing aws command"
 	aws --version 2>&1
 	if [ "$?" -gt 0 ]; then
-		error "Error while executing aws command as user root! Please check if AWS CLI tools (Python flavor) are properly installed and configured." && exit $OCF_ERR_INSTALLED
+		ocf_log error "Error while executing aws command as user root! Please check if AWS CLI tools (Python flavor) are properly installed and configured." && exit $OCF_ERR_INSTALLED
 	fi
 	debugger "ok"
 
