Medium: oracle: Create profile for OCFMON user (bnc#850589)
The OCFMON user needs to have unlimited password
expiry, otherwise the agent will fail if the
password expires. Create a profile OCFMONPROFILE
used by the OCFMON user with unlimited password
expiry.

Detect a previously created OCFMON user and alter
its profile to the new OCFMONPROFILE.

diff --git a/heartbeat/oracle b/heartbeat/oracle
--- a/heartbeat/oracle
+++ b/heartbeat/oracle
@@ -325,20 +325,60 @@ getipc() {
 	echo "oradebug tracefile_name"
 	echo "oradebug ipc"
 }
+show_mon_profile() {
+	echo "select PROFILE from dba_profiles where PROFILE='$MONPROFILE';"
+}
+mk_mon_profile() {
+	cat<<EOF
+create profile $MONPROFILE limit FAILED_LOGIN_ATTEMPTS UNLIMITED PASSWORD_LIFE_TIME UNLIMITED;
+EOF
+}
 show_mon_user() {
 	echo "select USERNAME, ACCOUNT_STATUS from dba_users where USERNAME='$MONUSR';"
 }
 mk_mon_user() {
 	cat<<EOF
-create user $MONUSR identified by $MONUSR;
+create user $MONUSR identified by $MONUSR profile $MONPROFILE;
 grant create session to $MONUSR;
 grant select on v_\$instance to $MONUSR;
 EOF
 }
+show_mon_user_profile() {
+	echo "select PROFILE from dba_users where USERNAME='$MONUSR';"
+}
+set_mon_user_profile() {
+	cat<<EOF
+alter user $MONUSR profile $MONPROFILE;
+EOF
+}
+check_mon_profile() {
+	local output
+	dbasql show_mon_profile | grep -w "^$MONPROFILE" >/dev/null &&
+		return 0
+	output=`dbasql mk_mon_profile show_mon_profile`
+	if echo "$output" | grep -w "^$MONPROFILE" >/dev/null; then
+		return 0
+	else
+		ocf_log err "could not create $MONPROFILE oracle profile"
+		ocf_log err "sqlplus output: $output"
+		return 1
+	fi
+}
 check_mon_user() {
 	local output
-	dbasql show_mon_user | grep -w "^$MONUSR" >/dev/null &&
-		return 0
+	output=`dbasql show_mon_user`
+	if echo "$output" | grep -w "^$MONUSR" >/dev/null; then
+		output=`dbasql show_mon_user_profile`
+		if echo "$output" | grep -w "^$MONPROFILE" >/dev/null; then
+			return 0
+		else
+			dbasql set_mon_user_profile | grep -w "^User altered." >/dev/null &&
+				return 0
+			ocf_log err "could not set profile for $MONUSR oracle user"
+			ocf_log err "sqlplus output: $output"
+			return 1
+		fi
+	fi
 	output=`dbasql mk_mon_user show_mon_user`
 	if echo "$output" | grep -w "^$MONUSR" >/dev/null; then
 		return 0
@@ -541,6 +581,11 @@ oracle_start() {
 	fi
 	output=`dbasql dbopen`
 
+	# check/create the monitor profile
+	if ! check_mon_profile; then
+		return $OCF_ERR_GENERIC
+	fi
+
 	# check/create the monitor user
 	if ! check_mon_user; then
 		return $OCF_ERR_GENERIC
@@ -650,6 +695,7 @@ show_procs() {
 proc_pids() { show_procs | awk '{print $1}'; }
 PROCS_CLEANUP_TIME="30"
 
+MONPROFILE="OCFMONPROFILE"
 MONUSR="OCFMON"
 OCF_REQUIRED_PARAMS="sid"
 OCF_REQUIRED_BINARIES="sqlplus"
